# -*- coding: utf-8 -*-
"""Amman model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p3lfPGOHZVRhwRpJ1-8rshPdKFKR3tOJ
"""

from google.colab import drive
drive.mount('/content/drive')

import os
print(os.listdir("/content"))

from google.colab import files
files.download("/content/whisperag_finetuned_amman_results.csv")

!pip install jiwer editdistance evaluate

import os
import re
import itertools
import numpy as np
import pandas as pd
import torch
import evaluate
import editdistance
from datasets import Dataset, Audio
from dataclasses import dataclass
from typing import Any, Dict, List, Union
from transformers import (
    WhisperForConditionalGeneration,
    WhisperProcessor,
    Seq2SeqTrainingArguments,
    Seq2SeqTrainer,
    EarlyStoppingCallback
)
from jiwer import wer

file_path = "/content/drive/MyDrive/cleaned_ag/ag_data.xlsx"
df = pd.read_excel(file_path)

df = df.rename(columns={"audio_path": "path", "Northern_aghwarDialect": "text"})

dataset = Dataset.from_pandas(df)
dataset = dataset.cast_column("path", Audio(sampling_rate=16000))

file_path = "/content/drive/MyDrive/cleaned_amman/Amman_data.xlsx"
df = pd.read_excel(file_path)

df = df.rename(columns={"audio_path": "path", "AmmanDialect": "text"})

dataset = Dataset.from_pandas(df)
dataset = dataset.cast_column("path", Audio(sampling_rate=16000))

from transformers import WhisperProcessor

processor = WhisperProcessor.from_pretrained("openai/whisper-large")

data_collator = DataCollatorWithPadding(processor=processor)

@dataclass
class DataCollatorWithPadding:
    processor: Any

    def __call__(self, features: List[Dict[str, Union[List[int], torch.Tensor]]]) -> Dict[str, torch.Tensor]:
        input_features = [{"input_features": feature["input_features"]} for feature in features]
        batch = self.processor.feature_extractor.pad(input_features, return_tensors="pt")

        if batch["input_features"].ndim == 4:
            batch["input_features"] = batch["input_features"].squeeze(1)
        label_features = [{"input_ids": feature["labels"]} for feature in features]
        labels_batch = self.processor.tokenizer.pad(label_features, return_tensors="pt")

        labels = labels_batch["input_ids"].masked_fill(labels_batch.attention_mask.ne(1), -100)
        batch["labels"] = labels

        return batch

data_collator = DataCollatorWithPadding(processor=processor)

wer_metric = evaluate.load("wer")
cer_metric = evaluate.load("cer")

def compute_metrics(eval_pred):
    predictions, labels = eval_pred
    labels = np.where(labels != -100, labels, processor.tokenizer.pad_token_id)

    pred_str = processor.tokenizer.batch_decode(predictions, skip_special_tokens=True)
    label_str = processor.tokenizer.batch_decode(labels, skip_special_tokens=True)
    wer_score = wer_metric.compute(predictions=pred_str, references=label_str)
    cer_score = cer_metric.compute(predictions=pred_str, references=label_str)

    return {"wer": wer_score * 100, "cer": cer_score * 100}

"""### **ag**"""

from transformers import WhisperForConditionalGeneration, WhisperProcessor
import torch
import pandas as pd
import soundfile as sf
import os

model_path = "/content/drive/MyDrive/whisper_medium_Amman_1e_8_adaaa_test_results_saved"

model = WhisperForConditionalGeneration.from_pretrained(
    model_path,
    use_safetensors=True
)

processor = WhisperProcessor.from_pretrained(model_path)

device = "cuda" if torch.cuda.is_available() else "cpu"
model.to(device)
model.eval()

file_path = "/content/drive/MyDrive/cleaned_ag/ag_data.xlsx"
df = pd.read_excel(file_path)

def fix_audio_path(old_path):
    if not isinstance(old_path, str):
        return old_path

    filename = os.path.basename(old_path)

    new_base_path = "/content/drive/MyDrive/cleaned_ag/audio/"
    return os.path.join(new_base_path, filename)

df["audio_path"] = df["audio_path"].apply(fix_audio_path)

results = []

for idx, row in df.iterrows():

    audio_file = row["audio_path"]
    reference_text = row["Northern_aghwarDialect"]

    try:
        audio_array, sr = sf.read(audio_file)

        inputs = processor(
            audio_array,
            sampling_rate=16000,
            return_tensors="pt"
        ).input_features.to(device)

        with torch.no_grad():
            predicted_ids = model.generate(inputs)

        transcription = processor.batch_decode(
            predicted_ids,
            skip_special_tokens=True
        )[0]

        results.append({
            "audio_file": audio_file,
            "reference": reference_text,
            "prediction": transcription
        })

        print(f"Processed {idx+1}/{len(df)}")

    except Exception as e:
        print(f"Error in {audio_file}: {e}")

results_df = pd.DataFrame(results)

results_df.to_csv(
    "whisper_AMMAN_finetuned_AG_results.csv",
    index=False,
    encoding="utf-8-sig"
)

print("✅ Saved:whisper_AMMAN_finetuned_AG_results.csv")

results_df = pd.read_csv("whisper_AMMAN_finetuned_AG_results.csv")

references = results_df["reference"].tolist()
predictions = results_df["prediction"].tolist()


wer_score = wer(references, predictions)


total_cer = sum(editdistance.eval(r, p) for r, p in zip(references, predictions))
total_chars = sum(len(r) for r in references)
cer_score = total_cer / total_chars

print(f"📊 Word Error Rate (WER): {wer_score:.4f}")
print(f"📊 Character Error Rate (CER): {cer_score:.4f}")

"""## **IRBID**"""

from transformers import WhisperForConditionalGeneration, WhisperProcessor
import torch
import pandas as pd
import soundfile as sf
import os


model_path = "/content/drive/MyDrive/whisper_medium_Amman_1e_8_adaaa_test_results_saved"

model = WhisperForConditionalGeneration.from_pretrained(
    model_path,
    use_safetensors=True
)

processor = WhisperProcessor.from_pretrained(model_path)

device = "cuda" if torch.cuda.is_available() else "cpu"
model.to(device)
model.eval()

file_path = "/content/drive/MyDrive/cleaned_irbid/irbid_data.xlsx"
df = pd.read_excel(file_path)

df["audio_path"] = df["audio_path"].apply(fix_audio_path)

results = []

for idx, row in df.iterrows():

    audio_file = row["audio_path"]
    reference_text = row["IrbidDialect"]

    try:
        audio_array, sr = sf.read(audio_file)

        inputs = processor(
            audio_array,
            sampling_rate=16000,
            return_tensors="pt"
        ).input_features.to(device)

        with torch.no_grad():
            predicted_ids = model.generate(inputs)

        transcription = processor.batch_decode(
            predicted_ids,
            skip_special_tokens=True
        )[0]

        results.append({
            "audio_file": audio_file,
            "reference": reference_text,
            "prediction": transcription
        })

        print(f"Processed {idx+1}/{len(df)}")

    except Exception as e:
        print(f"Error in {audio_file}: {e}")

# 4️⃣ حفظ النتائج
results_df = pd.DataFrame(results)

results_df.to_csv(
    "whisperAMMAN_finetuned_IRBID_results.csv",
    index=False,
    encoding="utf-8-sig"
)

print("✅ Saved:whisperAMMAN_finetuned_IRBID_results.csv")

results_df = pd.read_csv("whisperAMMAN_finetuned_IRBID_results.csv")

references = results_df["reference"].tolist()
predictions = results_df["prediction"].tolist()


wer_score = wer(references, predictions)


total_cer = sum(editdistance.eval(r, p) for r, p in zip(references, predictions))
total_chars = sum(len(r) for r in references)
cer_score = total_cer / total_chars

print(f"📊 Word Error Rate (WER): {wer_score:.4f}")
print(f"📊 Character Error Rate (CER): {cer_score:.4f}")