# -*- coding: utf-8 -*-
"""BEST_model_ag(Whispaer_large).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oMhHkgD6H4CZge55PkJ04LCR0lD0ZPO-

### **Environment Setup & Library Imports**
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install jiwer editdistance evaluate

import os
import re
import itertools
import numpy as np
import pandas as pd
import torch
import evaluate
import editdistance
from datasets import Dataset, Audio
from dataclasses import dataclass
from typing import Any, Dict, List, Union
from transformers import (
    WhisperForConditionalGeneration,
    WhisperProcessor,
    Seq2SeqTrainingArguments,
    Seq2SeqTrainer,
    EarlyStoppingCallback
)
from jiwer import wer

"""### **Dataset Preparation & Splitting**"""

file_path = "/content/drive/MyDrive/cleaned_ag/ag_data.xlsx"
df = pd.read_excel(file_path)

def fix_audio_path(old_path):
    if not isinstance(old_path, str):
        return old_path

    filename = os.path.basename(old_path)

    new_base_path = "/content/drive/MyDrive/cleaned_ag/audio/"
    return os.path.join(new_base_path, filename)


df["audio_path"] = df["audio_path"].apply(fix_audio_path)

df = df.rename(columns={"audio_path": "path", "Northern_aghwarDialect": "text"})
dataset = Dataset.from_pandas(df)
dataset = dataset.cast_column("path", Audio(sampling_rate=16000))

train_testvalid = dataset.train_test_split(test_size=0.3, seed=42)
test_valid = train_testvalid['test'].train_test_split(test_size=0.5, seed=42)

data_splits = {
    'train': train_testvalid['train'],
    'validation': test_valid['train'],
    'test': test_valid['test']
}

def clean_arabic_text(text):
    if not isinstance(text, str) or not text:
        return ""
    text = re.sub(r'[\u064B-\u0652]', '', text)
    text = re.sub(r'[إأآ]', 'ا', text)
    text = re.sub(r'[^\w\s\s]', '', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text

def prepare_example(batch):
    audio_data = batch["path"]
    audio_features = []
    for x in audio_data:
        raw_audio = x["array"]
        feature = processor(raw_audio, sampling_rate=16000).input_features[0]
        audio_features.append(feature)

    text_column = "text"
    cleaned_texts = [clean_arabic_text(t) for t in batch[text_column]]
    text_labels = [
        processor.tokenizer(t).input_ids
        for t in cleaned_texts
    ]

    return {"input_features": audio_features, "labels": text_labels}

save_folder = "/content/drive/MyDrive/pro_data/processed_ag_datasets"
os.makedirs(save_folder, exist_ok=True)

for split in ['train', 'validation', 'test']:
    cols_to_remove = data_splits[split].column_names
    data_splits[split] = data_splits[split].map(
        prepare_example,
        batched=True,
        remove_columns=cols_to_remove,
        batch_size=8
    )

    split_save_path = os.path.join(save_folder, split)

    print(f"{split} ")
    data_splits[split].save_to_disk(split_save_path)

    print(f"{split_save_path}\n")

from datasets import load_from_disk
import os

save_folder =  "/content/drive/MyDrive/pro_data/processed_ag_datasetsss"

train_dataset = load_from_disk(os.path.join(save_folder, 'train'))
val_dataset   = load_from_disk(os.path.join(save_folder, 'validation'))
test_dataset  = load_from_disk(os.path.join(save_folder, 'test'))

print(train_dataset)

@dataclass
class DataCollatorWithPadding:
    processor: Any

    def __call__(self, features: List[Dict[str, Union[List[int], torch.Tensor]]]) -> Dict[str, torch.Tensor]:
        input_features = [{"input_features": feature["input_features"]} for feature in features]
        batch = self.processor.feature_extractor.pad(input_features, return_tensors="pt")

        if batch["input_features"].ndim == 4:
            batch["input_features"] = batch["input_features"].squeeze(1)

        label_features = [{"input_ids": feature["labels"]} for feature in features]
        labels_batch = self.processor.tokenizer.pad(label_features, return_tensors="pt")


        labels = labels_batch["input_ids"].masked_fill(labels_batch.attention_mask.ne(1), -100)
        batch["labels"] = labels

        return batch

data_collator = DataCollatorWithPadding(processor=processor)

"""### **Model Configuration & Processor Setup**"""

model_name = "openai/whisper-large"

processor = WhisperProcessor.from_pretrained(model_name, language="arabic", task="transcribe")
forced_decoder_ids = processor.get_decoder_prompt_ids(language="arabic", task="transcribe")

wer_metric = evaluate.load("wer")
cer_metric = evaluate.load("cer")

def compute_metrics(eval_pred):
    predictions, labels = eval_pred
    labels = np.where(labels != -100, labels, processor.tokenizer.pad_token_id)
    pred_str = processor.tokenizer.batch_decode(predictions, skip_special_tokens=True)
    label_str = processor.tokenizer.batch_decode(labels, skip_special_tokens=True)

    wer_score = wer_metric.compute(predictions=pred_str, references=label_str)
    cer_score = cer_metric.compute(predictions=pred_str, references=label_str)

    return {"wer": wer_score * 100, "cer": cer_score * 100}

"""### **Hyperparameter Tuning Loop (Grid Search)**"""

num_epochs = 5
learning_rates = [1e-5]
batch_sizes = [8,4]
optimizers = ["adamw_torch"]

best_wer = float("inf")
best_config = None

for lr, bs, opt in itertools.product(learning_rates, batch_sizes, optimizers):
    print(f"\n=====   LR={lr}, Batch={bs}, Optimizer={opt} =====")

    grad_accum = 2 if bs < 16 else 1
    model = WhisperForConditionalGeneration.from_pretrained(model_name)

    model.config.use_cache = False

    model.generation_config.forced_decoder_ids = forced_decoder_ids
    model.generation_config.suppress_tokens = []

    training_args = Seq2SeqTrainingArguments(
        output_dir="./whisper_ag_tuning",
        per_device_train_batch_size=bs,
        per_device_eval_batch_size=max(1, bs // 2),
        gradient_accumulation_steps=grad_accum,
        eval_strategy="steps",
        num_train_epochs=num_epochs,
        save_steps=100,
        save_total_limit=1,
        logging_steps=50,
        learning_rate=lr,
        fp16=torch.cuda.is_available(),
        optim=opt,
        report_to="none",
        predict_with_generate=True,
        generation_max_length=225,
        load_best_model_at_end=True,
        metric_for_best_model="wer",
        greater_is_better=False,
        save_strategy="steps",
    )

    trainer = Seq2SeqTrainer(
        model=model,
        args=training_args,
        train_dataset=train_dataset,
        eval_dataset=val_dataset,
        data_collator=data_collator,
        compute_metrics=compute_metrics,
        callbacks=[EarlyStoppingCallback(early_stopping_patience=2)]
    )

    trainer.train()

    metrics = trainer.evaluate()
    val_wer = metrics.get("eval_wer", float("inf"))
    val_loss = metrics.get("eval_loss", float("inf"))
    print(f"   Validation Loss: {val_loss:.4f} | Validation WER: {val_wer:.2f}%")
    if val_wer < best_wer:
        best_wer = val_wer
        best_config = (lr, bs, opt)
        trainer.save_model("./best_whisperlarge_ag_1e_8_adam")
        processor.save_pretrained("./best_whisperlarge_ag_1e_8_adam")

print("\n Hyperparameters ")
print(f"Learning Rate: {best_config[0]} | Batch Size: {best_config[1]} | Optimizer: {best_config[2]}")
print(f"Best Validation WER: {best_wer:.2f}%")

print("\n(Test Set)...")

device = "cuda" if torch.cuda.is_available() else "cpu"
model_path = "./best_whisperlarge_ag_1e_8_adam"
best_model = WhisperForConditionalGeneration.from_pretrained(model_path).to(device)
best_processor = WhisperProcessor.from_pretrained(model_path)

best_model.eval()
test_dataset = test_dataset

predictions = []

for sample in test_dataset:
    inputs = torch.tensor(sample["input_features"]).unsqueeze(0).to(device)

    with torch.no_grad():

        predicted_ids = best_model.generate(
            inputs,
            language="arabic",
            task="transcribe"
        )

    transcription = best_processor.batch_decode(predicted_ids, skip_special_tokens=True)[0]
    reference = best_processor.tokenizer.decode(sample["labels"], skip_special_tokens=True)

    predictions.append({
        "reference": clean_arabic_text(reference),
        "prediction": clean_arabic_text(transcription)
    })


final_references = [p["reference"] for p in predictions]
final_hypotheses = [p["prediction"] for p in predictions]

test_wer_score = wer(final_references, final_hypotheses)
total_cer = sum(editdistance.eval(r, h) for r, h in zip(final_references, final_hypotheses))
total_chars = sum(len(r) for r in final_references) if sum(len(r) for r in final_references) > 0 else 1
test_cer_score = total_cer / total_chars

print(f"\n ")
print(f" WER على Test set: {test_wer_score * 100:.2f}%")
print(f" CER على Test set: {test_cer_score * 100:.2f}%")


pd.DataFrame(predictions).to_csv("whisper_large_ag_1e_8_adam_test_results.csv", index=False)
print(" whisper_large_ag_1e_8_adam_test_results.csv")

"""### **Zero-Shot Baseline Evaluation (Pre-training)**"""

from transformers import WhisperForConditionalGeneration, WhisperProcessor
import torch
import pandas as pd
import soundfile as sf


model_name = "openai/whisper-large"
model = WhisperForConditionalGeneration.from_pretrained(model_name)
processor = WhisperProcessor.from_pretrained(model_name)

device = "cuda" if torch.cuda.is_available() else "cpu"
model.to(device)
model.eval()

import pandas as pd
file_path = "/content/drive/MyDrive/cleaned_ag/ag_data.xlsx"
df = pd.read_excel(file_path)

def fix_audio_path(old_path):
    if not isinstance(old_path, str):
        return old_path
    filename = os.path.basename(old_path)
    new_base_path = "/content/drive/MyDrive/cleaned_ag/audio/"
    return os.path.join(new_base_path, filename)

df["audio_path"] = df["audio_path"].apply(fix_audio_path)

results = []

for idx, row in df.iterrows():
    audio_file = row["audio_path"]
    reference_text = row["Northern_aghwarDialect"]

    audio_array, sr = sf.read(audio_file)
    inputs = processor(audio_array, sampling_rate=16000, return_tensors="pt").input_features.to(device)
    with torch.no_grad():
        predicted_ids = model.generate(inputs)

    transcription = processor.batch_decode(predicted_ids, skip_special_tokens=True)[0]

    results.append({
        "audio_file": audio_file,
        "reference": reference_text,
        "prediction": transcription
    })

pd.DataFrame(results).to_csv("whisper_large_without_training_results.csv", index=False)
print("✅whisper_large_without_training_results.csv")

results_df = pd.read_csv("whisper_large_without_training_results.csv")

references = results_df["reference"].tolist()
predictions = results_df["prediction"].tolist()


wer_score = wer(references, predictions)


total_cer = sum(editdistance.eval(r, p) for r, p in zip(references, predictions))
total_chars = sum(len(r) for r in references)
cer_score = total_cer / total_chars

print(f"📊 Word Error Rate (WER): {wer_score:.4f}")
print(f"📊 Character Error Rate (CER): {cer_score:.4f}")

"""### **Performance Comparison (Before vs. After Fine-Tuning)**"""

before_df = pd.read_csv("whisper_large_without_training_results.csv")
after_df = pd.read_csv("whisper_large_ag_1e_8_adam_test_results.csv")

def compute_metrics(df):
    refs = df["reference"].tolist()
    preds = df["prediction"].tolist()
    wer_score = wer(refs, preds)
    total_cer = sum(editdistance.eval(r, p) for r, p in zip(refs, preds))
    total_chars = sum(len(r) for r in refs)
    cer_score = total_cer / total_chars
    return wer_score*100, cer_score*100

wer_before, cer_before = compute_metrics(before_df)
wer_after, cer_after = compute_metrics(after_df)

plt.figure(figsize=(8,5))
plt.bar(["WER Before","WER After"], [wer_before, wer_after], color=["red","green"])
plt.title("Word Error Rate Comparison")
plt.ylabel("WER (%)")
plt.show()

plt.figure(figsize=(8,5))
plt.bar(["CER Before","CER After"], [cer_before, cer_after], color=["orange","blue"])
plt.title("Character Error Rate Comparison")
plt.ylabel("CER (%)")
plt.show()